# Generated by Django 4.2.3 on 2023-07-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('operational_status', models.BooleanField(default=True)),
                ('current_floor', models.IntegerField(choices=[(1, 'First floor'), (2, 'second foor'), (3, 'Third floor'), (4, 'Fourth foor'), (5, 'Fifth floor'), (6, 'sixth foor')])),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stopped', 'Stopped')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='userRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_floor', models.IntegerField(choices=[(1, 'First floor'), (2, 'second foor'), (3, 'Third floor'), (4, 'Fourth foor'), (5, 'Fifth floor'), (6, 'sixth foor')])),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=5)),
            ],
        ),
    ]
